include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - download
  - build
  - scan

download:
  variables:
    GIT_STRATEGY: none
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  before_script:
    - apk add --no-cache curl grep
  script:
    - VERSION=$(wget -qO- https://github.com/memcached/memcached/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}')
    - curl -L https://github.com/memcached/memcached/archive/${VERSION}.tar.gz -o memcached.tar.gz
    - echo ${VERSION} > version.txt
  artifacts:
    expire_in: 1 day
    paths:
      - version.txt
      - memcached.tar.gz
  only:
    refs:
      - master

build:
  dependencies:
    - download
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - VERSION=$(cat version.txt)
    - TAG_LIST=$(helper "jitesoft/memcached,${CI_REGISTRY_IMAGE}" "latest,${VERSION}")
    - docker buildx build --platform "linux/amd64,linux/ppc64le,linux/s390x" --progress plain --push ${TAG_LIST} --build-arg VERSION_NUMBER=${VERSION} .
    - docker pull jitesoft/memcached:latest
    - docker tag jitesoft/memcached:latest quay.io/jitesoft/memcached:latest
    - docker tag jitesoft/memcached:latest quay.io/jitesoft/memcached:${VERSION}
    - docker push quay.io/jitesoft/memcached:latest
    - docker push quay.io/jitesoft/memcached:${VERSION}
  only:
    refs:
      - master
  tags: [jitesoft,arm64,amd64,ppc64le,s390x]

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
