include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - download
  - build
  - scan

download:
  variables:
    GIT_STRATEGY: none
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  before_script:
    - apk add --no-cache curl grep
  script:
    - VERSION=$(wget -qO- https://github.com/memcached/memcached/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}')
    - curl -L https://github.com/memcached/memcached/archive/${VERSION}.tar.gz -o memcached.tar.gz
    - echo ${VERSION} > version.txt
  artifacts:
    expire_in: 1 day
    paths:
      - version.txt
      - memcached.tar.gz
  only:
    refs:
      - master

build:
  dependencies:
    - download
  stage: build
  variables:
    TAGS: 'latest'
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  script:
    - VERSION=$(cat version.txt)
    - docker build --build-arg VERSION_NUMBER=${VERSION} --label "com.jitesoft.app.memcached.version=${VERSION}" -t ${CI_REGISTRY_IMAGE}:${VERSION} .
    - TAGS="${TAGS} ${VERSION}"
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${VERSION} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${VERSION} jitesoft/memcached:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${VERSION} quay.io/jitesoft/memcached:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
        docker push jitesoft/memcached:${tag}
        docker push quay.io/jitesoft/memcached:${tag}
      done
  only:
    refs:
      - master

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
